name = "LinearAlgebra"
uuid = "718410f4-c46a-4efc-accd-7788af733c5b"
authors = ["jin-park <jinparkdevelop@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
